'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ja' | 'ru' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.about': 'About Me',
    'nav.presentation': 'Presentation',
    'nav.experience': 'Experience',
    'nav.services': 'Services',
    'nav.awards': 'Awards',
    'nav.work': 'Work',
    'nav.contact': 'Contact',
    'hero.title': 'Creative Developer',
    'hero.subtitle': 'Building digital experiences',
    'hero.cta': 'View Work',
    'hero.editor': 'EDITOR',
    'hero.award_winning': '[ Award-winning Video Editor & Motion Designer ]',
    'hero.sys_status': 'SYS.STATUS: OPTIMAL',
    'hero.mem_usage': 'MEM.USAGE: 42.8%',
    'hero.db_conn': 'DB.CONN: ESTABLISHED',
    'hero.target': 'TARGET: IDENTIFIED',
    'hero.mode': 'MODE: CREATIVE',
    'hero.vfx': 'VFX_PIPELINE: ACTIVE',
    'hero.featured': 'FEATURED_ARCHIVES',
    'hero.scroll': 'SCROLL',
    'about.title': 'About Me',
    'about.bio': 'Biography',
    'about.skills': 'Skills',
    'about.software': 'Software Toolkit',
    'about.education': 'Education',
    'about.languages': 'Languages',
    'about.philosophy': 'Philosophy',
    'about.frontend': 'Frontend Dev',
    'about.video': 'Video Editor',
    'about.sound': 'Sound Designer',
    'about.motion': 'Motion Designer',
    'presentation.title': 'Presentation',
    'presentation.subtitle': 'PORTFOLIO DECK',
    'presentation.status': 'STATUS:',
    'presentation.online': 'ONLINE',
    'presentation.data_stream': 'DATA_STREAM_ACTIVE',
    'presentation.encryption': 'ENCRYPTION: NONE',
    'presentation.open_external': 'OPEN_EXTERNAL',
    'experience.title': 'Experience',
    'experience.personal_log': 'Personal_Data_Log',
    'experience.log_1': '> I’ve spent the last 6 years mastering the art of the edit. My background in the competitive AMV scene taught me the importance of frame-perfect timing my work with top-tier creators taught me how to engage an audience.',
    'experience.log_2': '> I don\'t just put clips together, I build an experience. With 6 years of experience, I’ve transitioned from winning anime editing contests to providing high-level video solutions for creators like Braxaphone and Saintontas.',
    'experience.log_3': '> Currently, I’m bridging the gap between traditional editing and motion design, ensuring your project isn\'t just watched, but felt.',
    'experience.end_log': '[ END OF LOG ]',
    'services.title': 'Services',
    'services.system_data': 'SYSTEM_DATA',
    'services.analyzing': '> Analyzing_Combat_Data...',
    'services.encrypted': '[ ENCRYPTED ]',
    'services.error': 'ERROR_404',
    'services.warning': '[ WARNING: DATA CORRUPTION ]',
    'services.scroll': 'Scroll to Decrypt',
    'services.assets': 'Assets &\nData',
    'services.equipment_log': 'Equipment_Log',
    'services.gear': 'GEAR',
    'services.desc_1': '> Level up your motion design with my custom After Effects presets and SFX!',
    'services.desc_2': '> All the secrets to achieving that high-energy, award-winning look. You\'ll find the exact animation curves, transition effects, and sound design essentials that I use in my everyday workflow for top-tier creators.',
    'services.item_1_title': '50+ Signature After Effects Presets.',
    'services.item_1_desc': 'Drag-and-drop motion curves, glitch maps, and shakes for AE.',
    'services.item_2_title': 'Elite "Sonic Impact" SFX Library.',
    'services.item_2_desc': 'Essential sound design for punchy transitions and tactile edits.',
    'services.item_3_title': 'Pro-Grade Flow Transitions.',
    'services.item_3_desc': 'Seamless, motion-blurred transitions for Premiere Pro & After Effects.',
    'services.details': '[ DETAILS ]',
    'services.acquire': '[ ACQUIRE ]',
    'awards.title': 'AWARDS',
    'awards.achievement_loaded': 'Achievement_Database_Loaded',
    'awards.record': 'Record',
    'awards.best_editing': 'BEST EDITING',
    'awards.judges_choice': 'JUDGES CHOICE',
    'awards.1st_place': '1ST PLACE',
    'awards.most_impactful': 'MOST IMPACTFUL',
    'awards.1st_place_exclusive': '1ST PLACE (EXCLUSIVE)',
    'awards.1st_place_open': '1ST PLACE (OPEN)',
    'work.title': 'Work',
    'work.system_data': '[ SYSTEM DATA // WORK_LOG ] • ',
    'work.category_amvs': 'AMVs / Edits',
    'work.category_creators': 'Content Creators',
    'work.category_thumbnails': 'Thumbnails',
    'contact.title': 'Contact',
    'contact.data_link': 'DATA_LINK',
    'contact.establish_connection': 'Establish Connection',
    'contact.identifier': 'Identifier',
    'contact.name_placeholder': '[ NAME ]',
    'contact.comm_channel': 'Comm_Channel',
    'contact.email_placeholder': '[ EMAIL ]',
    'contact.payload': 'Payload',
    'contact.message_placeholder': '[ ENTER MESSAGE DATA ]',
    'contact.transmitting': '[ TRANSMITTING DATA... ]',
    'contact.transmit': '[ TRANSMIT ]',
    'contact.data_received': 'DATA RECEIVED',
    'contact.comm_established': 'Communication link established.',
    'contact.awaiting': 'Awaiting further instructions.',
    'contact.network_nodes': 'Network_Nodes',
    'contact.discord': 'DISCORD',
    'contact.copied': 'Username Copied successfully',
    'contact.youtube': 'YOUTUBE',
    'contact.twitter': 'X / TWITTER',
    'contact.secret_title': 'SECRET_DATA_FOUND',
    'contact.secret_desc': 'Thx for visiting my site! I poured my heart into this design. Keep creating and stay awesome.',
    'contact.close': '[ CLOSE ]',
    'about.bio_p1': "I didn't begin my career as a video editor. My path started in computer engineering and programming, leading to a Master’s degree in Informatics from BSU. Although I valued the logic behind coding, it never fully connected with me. What remained constant was my love for editing.",
    'about.bio_p2': "What started as a refuge editing anime clips to music to express my emotions transformed into a fiercely competitive field. Over the last 6 years, I have developed a career characterized by technical accuracy and creative influence, merging the engineering precision of my education with the pure enthusiasm of an AMV champion.",
    'about.bio_p3': "My work is deeply rooted in a passion for digital art from winning multiple Editing Tournaments to partnering with top tier content creators like Braxaphone, Glaivekiyo, and Saintontas. I don’t merely “complete projects”; I craft unforgettable visual experiences. Whether I’m constructing intricate After Effects compositions or designing narrative-driven cinematic openings, my aim remains consistent: to create experiences that are not only viewed but truly felt.",
    'about.skill_1_title': "Motion Design",
    'about.skill_1_desc': "An evolving discipline I continuously refine, already applied in creating high-level graphics and dynamic character guides inspired by game aesthetics.",
    'about.skill_2_title': "Video Editing",
    'about.skill_2_desc': "Capable of bringing any vision to life, transforming ideas into cinematic, engaging videos with strong visual storytelling.",
    'about.skill_3_title': "Sound Design",
    'about.skill_3_desc': "As passionate about sound as editing, I enhance videos with immersive, high-impact audio that elevates overall quality and emotion.",
    'about.skill_4_title': "Thumbnail Artistry",
    'about.skill_4_desc': "Designing high-conversion thumbnails that instantly capture attention and drive clicks through strong composition and visual clarity.",
    'about.skill_5_title': "VFX & Masking",
    'about.skill_5_desc': "Built through years of AMV experience, mastering rotoscoping, masking, and compositing using Adobe After Effects and Adobe Premiere Pro to significantly enhance visual depth and polish.",
    'about.skill_6_title': "Frontend Development",
    'about.skill_6_desc': "Building responsive, visually refined interfaces that merge design and functionality, with a focus on smooth interactions and performance-driven experiences.",
    'about.soft_1_title': "Adobe After Effects",
    'about.soft_1_desc': "Specialist in intricate keyframing, motion graphics, and high-end VFX.",
    'about.soft_2_title': "Adobe Premiere Pro",
    'about.soft_2_desc': "Expert in long-form narrative structure and rapid-turnaround cutting.",
    'about.soft_3_title': "Adobe Photoshop",
    'about.soft_3_desc': "Advanced digital manipulation for high-impact static assets and thumbnails.",
    'about.soft_4_title': "Sony Vegas Pro",
    'about.soft_4_desc': "Legacy expertise; the foundation of my editing career and rhythmic \"flow\" style.",
    'about.edu_1_title': "Master of Science: Informatics",
    'about.edu_1_desc': "Advanced focus on information systems and algorithmic logic. This academic foundation allows me to approach complex project structures and data management with a systematic, high-level perspective.",
    'about.edu_2_title': "Bachelor of Science: Computer Engineering",
    'about.edu_2_desc': "Fundamental engineering principles. My background in hardware architecture and system optimization provides a distinct advantage in managing heavy rendering workloads and complex software integrations.",
    'about.edu_3_title': "Professional Diploma: Digital Design",
    'about.edu_3_desc': "A multi-disciplinary program where I bridged the gap between Front-End Development, Professional Video Editing, and Visual Retouching. This is where my technical engineering roots met professional creative production.",
    'about.lang_1': "Azerbaijani",
    'about.lang_1_level': "Native",
    'about.lang_2': "Russian",
    'about.lang_2_level': "Bilingual",
    'about.lang_3': "English",
    'about.lang_3_level': "Professional Working Proficiency",
    'about.lang_4': "Turkish",
    'about.lang_4_level': "Professional Working Proficiency",
    'about.philosophy_log': "System.Log // Philosophy",
    'about.philosophy_quote': "\"My background as a Computer Engineer means I don't just use creative software; I understand the architecture behind it. This technical depth allows me to optimize performance, troubleshoot complex VFX pipelines, and maintain peak visual quality in high-pressure environments.\"",
    'experience.ethin_role': "Designer and Editor",
    'experience.ethin_loc': "Remote",
    'experience.ethin_det_1': "High-Impact Thumbnails Creating clickable, high-fidelity art using advanced lighting and composition techniques.",
    'experience.ethin_det_2': "Acted as a dedicated creative partner, providing rapid-response support for all production needs.",
    'experience.ethin_det_3': "Leveraged technical proficiency to manage multi-disciplinary tasks from Photoshop compositions to creating Videos for chanel without compromising quality.",
    'experience.glaivekiyo_role': "Lead Editor",
    'experience.glaivekiyo_loc': "Remote",
    'experience.glaivekiyo_det_1': "Revolutionized channel visual identity, evolving standard formats into high-engagement narratives through creative pacing.",
    'experience.glaivekiyo_det_2': "Mastered \"Retention Editing,\" utilizing rhythmic cutting and subtle motion cues to maximize viewer immersion.",
    'experience.glaivekiyo_det_3': "Standardized high-fidelity workflows, delivering professional-grade visual quality that redefined the channel’s production value.",
    'experience.glaivekiyo_det_4': "Redefined creative direction, shifting the video-making style to prioritize a professional, high-impact aesthetic.",
    'experience.braxophone_role': "Editor",
    'experience.braxophone_loc': "Remote",
    'experience.braxophone_det_1': "Executed high-precision post-production, managing granular feedback loops to ensure every frame met elite-level quality standards.",
    'experience.braxophone_det_2': "Mastered rigorous quality assurance, delivering frame-perfect revisions through extended production cycles without compromising project integrity.",
    'experience.braxophone_det_3': "Maintained 100% project completion rates, demonstrating extreme reliability and dedication to meeting complex, high-pressure deadlines.",
    'experience.saintontas_role': "Motion Designer , Editor",
    'experience.saintontas_loc': "Remote",
    'experience.saintontas_det_1': "Developed unique A-roll graphics to transform complex data into high-retention motion assets.",
    'experience.saintontas_det_2': "Engineered bespoke \"Intro Edits\" for character guides, creating distinct visual identities through high-impact sync.",
    'experience.saintontas_det_3': "Integrated advanced VFX and masking to elevate standard tutorials into cinematic experiences.",
    'experience.saintontas_det_4': "Leveraged 6 years of expertise in competitive AMV production to deliver professional-grade sound design and \"flow.\"",
    'experience.mrpokke_role': "Video Editor",
    'experience.mrpokke_loc': "Remote",
    'experience.mrpokke_det_1': "Curated high-engagement video content, synthesizing raw stream archives into polished, high-quality narratives for the main channel.",
    'experience.mrpokke_det_2': "Mastered audience retention techniques, identifying and isolating \"must-watch\" moments to drive consistent viewer growth.",
    'experience.mrpokke_det_3': "Maintained peak visual consistency, ensuring each upload aligned with the channel's high standards for pacing and clarity.",
    'experience.villainarc_role': "Editor",
    'experience.villainarc_loc': "Remote",
    'experience.villainarc_det_1': "Produced high-impact, stylized Anime Edits for a specialized crypto agency, blending high-energy visual aesthetics with corporate messaging to capture a modern, digital-native audience.",
    'experience.villainarc_det_2': "Mastered rapid-turnaround workflows for high-volume video series, ensuring professional-grade visual quality while meeting the fast-paced demands of the crypto industry.",
  },
  ja: {
    'nav.about': '私について',
    'nav.presentation': 'プレゼンテーション',
    'nav.experience': '経験',
    'nav.services': 'サービス',
    'nav.awards': '受賞歴',
    'nav.work': '作品',
    'nav.contact': '連絡先',
    'hero.title': 'クリエイティブ開発者',
    'hero.subtitle': 'デジタル体験の構築',
    'hero.cta': '作品を見る',
    'hero.editor': 'エディター',
    'hero.award_winning': '[ 受賞歴のあるビデオエディター＆モーションデザイナー ]',
    'hero.sys_status': 'SYS.STATUS: 最適',
    'hero.mem_usage': 'MEM.USAGE: 42.8%',
    'hero.db_conn': 'DB.CONN: 確立',
    'hero.target': 'TARGET: 識別済',
    'hero.mode': 'MODE: クリエイティブ',
    'hero.vfx': 'VFX_PIPELINE: アクティブ',
    'hero.featured': '注目のアーカイブ',
    'hero.scroll': 'スクロール',
    'about.title': '私について',
    'about.bio': '経歴',
    'about.skills': 'スキル',
    'about.software': 'ソフトウェア',
    'about.education': '教育',
    'about.languages': '言語',
    'about.philosophy': '哲学',
    'about.frontend': 'フロントエンド開発',
    'about.video': 'ビデオ編集',
    'about.sound': 'サウンドデザイン',
    'about.motion': 'モーションデザイン',
    'presentation.title': 'プレゼンテーション',
    'presentation.subtitle': 'ポートフォリオデッキ',
    'presentation.status': 'ステータス:',
    'presentation.online': 'オンライン',
    'presentation.data_stream': 'データストリーム_アクティブ',
    'presentation.encryption': '暗号化: なし',
    'presentation.open_external': '外部で開く',
    'experience.title': '経験',
    'experience.personal_log': '個人データログ',
    'experience.log_1': '> 過去6年間、編集の技術を極めてきました。競争の激しいAMVシーンでの経験は、フレーム単位の完璧なタイミングの重要性を教えてくれ、トップクリエイターとの仕事は視聴者を惹きつける方法を教えてくれました。',
    'experience.log_2': '> 単にクリップをつなぎ合わせるのではなく、体験を構築します。6年の経験を経て、アニメ編集コンテストでの優勝から、BraxaphoneやSaintontasのようなクリエイターにハイレベルなビデオソリューションを提供するまでに成長しました。',
    'experience.log_3': '> 現在は、伝統的な編集とモーションデザインのギャップを埋め、プロジェクトが単に見られるだけでなく、感じられるようにしています。',
    'experience.end_log': '[ ログ終了 ]',
    'services.title': 'サービス',
    'services.system_data': 'システムデータ',
    'services.analyzing': '> 戦闘データを解析中...',
    'services.encrypted': '[ 暗号化 ]',
    'services.error': 'エラー_404',
    'services.warning': '[ 警告: データ破損 ]',
    'services.scroll': 'スクロールして復号化',
    'services.assets': 'アセット &\nデータ',
    'services.equipment_log': '装備ログ',
    'services.gear': 'ギア',
    'services.desc_1': '> カスタムAfter EffectsプリセットとSFXでモーションデザインをレベルアップ！',
    'services.desc_2': '> 受賞歴のあるハイエナジーなルックを実現するためのすべての秘密。トップクリエイター向けの日常のワークフローで使用している、正確なアニメーションカーブ、トランジションエフェクト、サウンドデザインの必須要素が見つかります。',
    'services.item_1_title': '50以上のシグネチャーAfter Effectsプリセット。',
    'services.item_1_desc': 'AE用のドラッグアンドドロップモーションカーブ、グリッチマップ、シェイク。',
    'services.item_2_title': 'エリート「ソニックインパクト」SFXライブラリ。',
    'services.item_2_desc': 'パンチの効いたトランジションと触覚的な編集に不可欠なサウンドデザイン。',
    'services.item_3_title': 'プログレードのフロートランジション。',
    'services.item_3_desc': 'Premiere ProとAfter Effects用のシームレスでモーションブラーのかかったトランジション。',
    'services.details': '[ 詳細 ]',
    'services.acquire': '[ 取得 ]',
    'awards.title': '受賞歴',
    'awards.achievement_loaded': '実績データベース読み込み完了',
    'awards.record': '記録',
    'awards.best_editing': 'ベストエディティング',
    'awards.judges_choice': '審査員特別賞',
    'awards.1st_place': '1位',
    'awards.most_impactful': '最もインパクトのある作品',
    'awards.1st_place_exclusive': '1位 (エクスクルーシブ)',
    'awards.1st_place_open': '1位 (オープン)',
    'work.title': '作品',
    'work.system_data': '[ システムデータ // ワークログ ] • ',
    'work.category_amvs': 'AMV / 編集',
    'work.category_creators': 'コンテンツクリエイター',
    'work.category_thumbnails': 'サムネイル',
    'contact.title': '連絡先',
    'contact.data_link': 'データリンク',
    'contact.establish_connection': '接続を確立',
    'contact.identifier': '識別子',
    'contact.name_placeholder': '[ 名前 ]',
    'contact.comm_channel': '通信チャンネル',
    'contact.email_placeholder': '[ メールアドレス ]',
    'contact.payload': 'ペイロード',
    'contact.message_placeholder': '[ メッセージデータを入力 ]',
    'contact.transmitting': '[ データ送信中... ]',
    'contact.transmit': '[ 送信 ]',
    'contact.data_received': 'データ受信完了',
    'contact.comm_established': '通信リンクが確立されました。',
    'contact.awaiting': 'さらなる指示を待っています。',
    'contact.network_nodes': 'ネットワークノード',
    'contact.discord': 'DISCORD',
    'contact.copied': 'ユーザー名が正常にコピーされました',
    'contact.youtube': 'YOUTUBE',
    'contact.twitter': 'X / TWITTER',
    'contact.secret_title': '秘密のデータを発見',
    'contact.secret_desc': 'サイトを訪問してくれてありがとう！このデザインには心を込めました。これからも素晴らしい作品を作り続けてください。',
    'contact.close': '[ 閉じる ]',
    'about.bio_p1': "私のキャリアはビデオエディターとして始まったわけではありません。コンピュータエンジニアリングとプログラミングの道から始まり、BSUで情報学の修士号を取得しました。コーディングの背後にある論理を評価していましたが、完全に自分と結びつくことはありませんでした。常に変わらなかったのは、編集への愛でした。",
    'about.bio_p2': "感情を表現するためにアニメクリップを音楽に合わせて編集する避難所として始まったものが、激しい競争の場へと変貌しました。過去6年間、私は技術的な正確さと創造的な影響力を特徴とするキャリアを築き、教育のエンジニアリングの精度とAMVチャンピオンの純粋な熱意を融合させてきました。",
    'about.bio_p3': "私の仕事は、複数の編集トーナメントでの優勝から、Braxaphone、Glaivekiyo、Saintontasなどのトップティアのコンテンツクリエイターとのパートナーシップまで、デジタルアートへの情熱に深く根ざしています。私は単に「プロジェクトを完了する」のではなく、忘れられない視覚体験を作り出します。複雑なAfter Effectsのコンポジションを構築する場合でも、物語主導のシネマティックなオープニングをデザインする場合でも、私の目的は一貫しています。それは、単に見られるだけでなく、真に感じられる体験を作り出すことです。",
    'about.skill_1_title': "モーションデザイン",
    'about.skill_1_desc': "常に洗練させている進化する分野であり、ゲームの美学に触発されたハイレベルなグラフィックやダイナミックなキャラクターガイドの作成にすでに適用されています。",
    'about.skill_2_title': "ビデオ編集",
    'about.skill_2_desc': "あらゆるビジョンを実現し、アイデアを強力な視覚的ストーリーテリングを備えたシネマティックで魅力的なビデオに変換する能力。",
    'about.skill_3_title': "サウンドデザイン",
    'about.skill_3_desc': "編集と同じくらいサウンドに情熱を注いでおり、没入感のあるインパクトのあるオーディオでビデオを強化し、全体的な品質と感情を高めます。",
    'about.skill_4_title': "サムネイルアート",
    'about.skill_4_desc': "強力な構図と視覚的な明瞭さを通じて、瞬時に注意を引き、クリックを促進する高コンバージョンのサムネイルをデザインします。",
    'about.skill_5_title': "VFXとマスキング",
    'about.skill_5_desc': "長年のAMVの経験を通じて構築され、Adobe After EffectsとAdobe Premiere Proを使用してロトスコープ、マスキング、合成を習得し、視覚的な深みと洗練度を大幅に向上させます。",
    'about.skill_6_title': "フロントエンド開発",
    'about.skill_6_desc': "デザインと機能を融合させた、レスポンシブで視覚的に洗練されたインターフェースを構築し、スムーズなインタラクションとパフォーマンス主導の体験に焦点を当てます。",
    'about.soft_1_title': "Adobe After Effects",
    'about.soft_1_desc': "複雑なキーフレーム、モーショングラフィックス、ハイエンドVFXのスペシャリスト。",
    'about.soft_2_title': "Adobe Premiere Pro",
    'about.soft_2_desc': "長編の物語構造と迅速なカットの専門家。",
    'about.soft_3_title': "Adobe Photoshop",
    'about.soft_3_desc': "インパクトのある静的アセットとサムネイルのための高度なデジタル操作。",
    'about.soft_4_title': "Sony Vegas Pro",
    'about.soft_4_desc': "レガシーな専門知識。私の編集キャリアとリズミカルな「フロー」スタイルの基盤。",
    'about.edu_1_title': "理学修士：情報学",
    'about.edu_1_desc': "情報システムとアルゴリズム論理に焦点を当てた高度な学習。この学術的基盤により、体系的で高レベルな視点から複雑なプロジェクト構造とデータ管理に取り組むことができます。",
    'about.edu_2_title': "理学士：コンピュータエンジニアリング",
    'about.edu_2_desc': "基本的なエンジニアリングの原則。ハードウェアアーキテクチャとシステム最適化のバックグラウンドは、重いレンダリングワークロードと複雑なソフトウェア統合を管理する上で明確な利点を提供します。",
    'about.edu_3_title': "プロフェッショナルディプロマ：デジタルデザイン",
    'about.edu_3_desc': "フロントエンド開発、プロのビデオ編集、ビジュアルレタッチのギャップを埋めた学際的なプログラム。ここで私の技術的なエンジニアリングのルーツがプロのクリエイティブ制作と出会いました。",
    'about.lang_1': "アゼルバイジャン語",
    'about.lang_1_level': "ネイティブ",
    'about.lang_2': "ロシア語",
    'about.lang_2_level': "バイリンガル",
    'about.lang_3': "英語",
    'about.lang_3_level': "ビジネスレベル",
    'about.lang_4': "トルコ語",
    'about.lang_4_level': "ビジネスレベル",
    'about.philosophy_log': "System.Log // 哲学",
    'about.philosophy_quote': "\"コンピュータエンジニアとしての私のバックグラウンドは、単にクリエイティブなソフトウェアを使用するだけでなく、その背後にあるアーキテクチャを理解していることを意味します。この技術的な深みにより、パフォーマンスを最適化し、複雑なVFXパイプラインのトラブルシューティングを行い、プレッシャーの高い環境で最高の視覚的品質を維持することができます。\"",
    'experience.ethin_role': "デザイナー兼エディター",
    'experience.ethin_loc': "リモート",
    'experience.ethin_det_1': "高度な照明と構図のテクニックを使用して、クリック可能で忠実度の高いアートを作成するインパクトのあるサムネイル。",
    'experience.ethin_det_2': "専任のクリエイティブパートナーとして行動し、すべての制作ニーズに迅速に対応するサポートを提供しました。",
    'experience.ethin_det_3': "技術的な習熟度を活用して、品質を損なうことなく、Photoshopのコンポジションからチャンネル用のビデオ作成まで、学際的なタスクを管理しました。",
    'experience.glaivekiyo_role': "リードエディター",
    'experience.glaivekiyo_loc': "リモート",
    'experience.glaivekiyo_det_1': "チャンネルの視覚的アイデンティティに革命をもたらし、クリエイティブなペース配分を通じて標準フォーマットをエンゲージメントの高い物語に進化させました。",
    'experience.glaivekiyo_det_2': "リズミカルなカッティングと微妙なモーションキューを利用して視聴者の没入感を最大化する「リテンション編集」を習得しました。",
    'experience.glaivekiyo_det_3': "忠実度の高いワークフローを標準化し、チャンネルの制作価値を再定義するプロフェッショナルグレードの視覚的品質を提供しました。",
    'experience.glaivekiyo_det_4': "クリエイティブな方向性を再定義し、ビデオ制作のスタイルをプロフェッショナルでインパクトのある美学を優先するようにシフトしました。",
    'experience.braxophone_role': "エディター",
    'experience.braxophone_loc': "リモート",
    'experience.braxophone_det_1': "高精度のポストプロダクションを実行し、詳細なフィードバックループを管理して、すべてのフレームがエリートレベルの品質基準を満たすようにしました。",
    'experience.braxophone_det_2': "厳格な品質保証を習得し、プロジェクトの整合性を損なうことなく、長期間の制作サイクルを通じてフレームパーフェクトな修正を提供しました。",
    'experience.braxophone_det_3': "100%のプロジェクト完了率を維持し、複雑でプレッシャーの高い締め切りを満たすための極めて高い信頼性と献身を示しました。",
    'experience.saintontas_role': "モーションデザイナー、エディター",
    'experience.saintontas_loc': "リモート",
    'experience.saintontas_det_1': "複雑なデータを高いリテンションのモーションアセットに変換するための独自のAロールグラフィックを開発しました。",
    'experience.saintontas_det_2': "キャラクターガイド用の特注の「イントロ編集」を設計し、インパクトのある同期を通じて明確な視覚的アイデンティティを作成しました。",
    'experience.saintontas_det_3': "高度なVFXとマスキングを統合して、標準的なチュートリアルをシネマティックな体験に引き上げました。",
    'experience.saintontas_det_4': "競争の激しいAMV制作における6年間の専門知識を活用して、プロフェッショナルグレードのサウンドデザインと「フロー」を提供しました。",
    'experience.mrpokke_role': "ビデオエディター",
    'experience.mrpokke_loc': "リモート",
    'experience.mrpokke_det_1': "エンゲージメントの高いビデオコンテンツをキュレートし、生のストリームアーカイブをメインチャンネル用の洗練された高品質の物語に合成しました。",
    'experience.mrpokke_det_2': "視聴者維持のテクニックを習得し、「必見」の瞬間を特定して分離し、一貫した視聴者の成長を促進しました。",
    'experience.mrpokke_det_3': "最高の視覚的一貫性を維持し、各アップロードがペース配分と明瞭さに関するチャンネルの高い基準に一致するようにしました。",
    'experience.villainarc_role': "エディター",
    'experience.villainarc_loc': "リモート",
    'experience.villainarc_det_1': "専門の暗号通貨エージェンシー向けにインパクトのある様式化されたアニメ編集を制作し、高エネルギーの視覚的美学と企業メッセージを融合させて、現代のデジタルネイティブな視聴者を魅了しました。",
    'experience.villainarc_det_2': "大量のビデオシリーズの迅速なターンアラウンドワークフローを習得し、暗号通貨業界のペースの速い要求を満たしながら、プロフェッショナルグレードの視覚的品質を確保しました。",
  },
  ru: {
    'nav.about': 'Обо мне',
    'nav.presentation': 'Презентация',
    'nav.experience': 'Опыт',
    'nav.services': 'Услуги',
    'nav.awards': 'Награды',
    'nav.work': 'Работы',
    'nav.contact': 'Контакты',
    'hero.title': 'Креативный Разработчик',
    'hero.subtitle': 'Создание цифровых впечатлений',
    'hero.cta': 'Смотреть работы',
    'hero.editor': 'РЕДАКТОР',
    'hero.award_winning': '[ Отмеченный наградами видеоредактор и моушн-дизайнер ]',
    'hero.sys_status': 'SYS.STATUS: ОПТИМАЛЬНО',
    'hero.mem_usage': 'MEM.USAGE: 42.8%',
    'hero.db_conn': 'DB.CONN: УСТАНОВЛЕНО',
    'hero.target': 'TARGET: ИДЕНТИФИЦИРОВАНА',
    'hero.mode': 'MODE: КРЕАТИВНЫЙ',
    'hero.vfx': 'VFX_PIPELINE: АКТИВЕН',
    'hero.featured': 'ИЗБРАННЫЕ_АРХИВЫ',
    'hero.scroll': 'ПРОКРУТКА',
    'about.title': 'Обо мне',
    'about.bio': 'Биография',
    'about.skills': 'Навыки',
    'about.software': 'Программы',
    'about.education': 'Образование',
    'about.languages': 'Языки',
    'about.philosophy': 'Философия',
    'about.frontend': 'Frontend Разработчик',
    'about.video': 'Видеоредактор',
    'about.sound': 'Саунд-дизайнер',
    'about.motion': 'Моушн-дизайнер',
    'presentation.title': 'Презентация',
    'presentation.subtitle': 'ПОРТФОЛИО',
    'presentation.status': 'СТАТУС:',
    'presentation.online': 'ОНЛАЙН',
    'presentation.data_stream': 'ПОТОК_ДАННЫХ_АКТИВЕН',
    'presentation.encryption': 'ШИФРОВАНИЕ: НЕТ',
    'presentation.open_external': 'ОТКРЫТЬ_ВНЕШНЕ',
    'experience.title': 'Опыт',
    'experience.personal_log': 'Журнал_Личных_Данных',
    'experience.log_1': '> Последние 6 лет я посвятил совершенствованию искусства монтажа. Мой опыт в конкурентной среде AMV научил меня важности идеального тайминга, а работа с топовыми креаторами — тому, как удерживать внимание аудитории.',
    'experience.log_2': '> Я не просто склеиваю клипы, я создаю опыт. За 6 лет я прошел путь от побед в конкурсах аниме-монтажа до предоставления высокоуровневых видеорешений для таких креаторов, как Braxaphone и Saintontas.',
    'experience.log_3': '> В настоящее время я стираю грань между традиционным монтажом и моушн-дизайном, гарантируя, что ваш проект не просто посмотрят, а прочувствуют.',
    'experience.end_log': '[ КОНЕЦ ЖУРНАЛА ]',
    'services.title': 'Услуги',
    'services.system_data': 'СИСТЕМНЫЕ_ДАННЫЕ',
    'services.analyzing': '> Анализ_Боевых_Данных...',
    'services.encrypted': '[ ЗАШИФРОВАНО ]',
    'services.error': 'ОШИБКА_404',
    'services.warning': '[ ВНИМАНИЕ: ПОВРЕЖДЕНИЕ ДАННЫХ ]',
    'services.scroll': 'Прокрутите для расшифровки',
    'services.assets': 'Ассеты &\nДанные',
    'services.equipment_log': 'Журнал_Экипировки',
    'services.gear': 'СНАРЯЖЕНИЕ',
    'services.desc_1': '> Прокачайте свой моушн-дизайн с моими кастомными пресетами After Effects и SFX!',
    'services.desc_2': '> Все секреты достижения этого энергичного, отмеченного наградами вида. Вы найдете точные кривые анимации, эффекты переходов и основы саунд-дизайна, которые я использую в своей повседневной работе для топовых креаторов.',
    'services.item_1_title': '50+ Фирменных пресетов After Effects.',
    'services.item_1_desc': 'Кривые движения, карты глитчей и тряски для AE (drag-and-drop).',
    'services.item_2_title': 'Элитная библиотека SFX "Sonic Impact".',
    'services.item_2_desc': 'Необходимый саунд-дизайн для мощных переходов и тактильного монтажа.',
    'services.item_3_title': 'Плавные переходы профессионального уровня.',
    'services.item_3_desc': 'Бесшовные переходы с размытием в движении для Premiere Pro и After Effects.',
    'services.details': '[ ДЕТАЛИ ]',
    'services.acquire': '[ ПРИОБРЕСТИ ]',
    'awards.title': 'НАГРАДЫ',
    'awards.achievement_loaded': 'База_Достижений_Загружена',
    'awards.record': 'Запись',
    'awards.best_editing': 'ЛУЧШИЙ МОНТАЖ',
    'awards.judges_choice': 'ВЫБОР ЖЮРИ',
    'awards.1st_place': '1-Е МЕСТО',
    'awards.most_impactful': 'САМЫЙ ЭФФЕКТНЫЙ',
    'awards.1st_place_exclusive': '1-Е МЕСТО (ЭКСКЛЮЗИВ)',
    'awards.1st_place_open': '1-Е МЕСТО (ОТКРЫТАЯ КАТЕГОРИЯ)',
    'work.title': 'Работы',
    'work.system_data': '[ СИСТЕМНЫЕ ДАННЫЕ // ЖУРНАЛ_РАБОТ ] • ',
    'work.category_amvs': 'AMV / Монтаж',
    'work.category_creators': 'Контент-креаторы',
    'work.category_thumbnails': 'Превью',
    'contact.title': 'Контакты',
    'contact.data_link': 'КАНАЛ_ДАННЫХ',
    'contact.establish_connection': 'Установка Соединения',
    'contact.identifier': 'Идентификатор',
    'contact.name_placeholder': '[ ИМЯ ]',
    'contact.comm_channel': 'Канал_Связи',
    'contact.email_placeholder': '[ EMAIL ]',
    'contact.payload': 'Полезная_Нагрузка',
    'contact.message_placeholder': '[ ВВЕДИТЕ ДАННЫЕ СООБЩЕНИЯ ]',
    'contact.transmitting': '[ ПЕРЕДАЧА ДАННЫХ... ]',
    'contact.transmit': '[ ПЕРЕДАТЬ ]',
    'contact.data_received': 'ДАННЫЕ ПОЛУЧЕНЫ',
    'contact.comm_established': 'Канал связи установлен.',
    'contact.awaiting': 'Ожидание дальнейших инструкций.',
    'contact.network_nodes': 'Сетевые_Узлы',
    'contact.discord': 'DISCORD',
    'contact.copied': 'Имя пользователя успешно скопировано',
    'contact.youtube': 'YOUTUBE',
    'contact.twitter': 'X / TWITTER',
    'contact.secret_title': 'СЕКРЕТНЫЕ_ДАННЫЕ_НАЙДЕНЫ',
    'contact.secret_desc': 'Спасибо за посещение моего сайта! Я вложил душу в этот дизайн. Продолжайте творить и оставайтесь потрясающими.',
    'contact.close': '[ ЗАКРЫТЬ ]',
    'about.bio_p1': "Я не начинал свою карьеру как видеоредактор. Мой путь начался с компьютерной инженерии и программирования, что привело к получению степени магистра информатики в БГУ. Хотя я ценил логику кодинга, это никогда не было моим истинным призванием. Неизменной оставалась лишь моя любовь к монтажу.",
    'about.bio_p2': "То, что начиналось как отдушина — монтаж аниме-клипов под музыку для выражения эмоций — превратилось в высококонкурентную сферу. За последние 6 лет я построил карьеру, отличающуюся технической точностью и творческим влиянием, объединив инженерную строгость моего образования с чистым энтузиазмом чемпиона AMV.",
    'about.bio_p3': "Моя работа глубоко укоренена в страсти к цифровому искусству: от побед в многочисленных турнирах по монтажу до партнерства с топовыми контент-креаторами, такими как Braxaphone, Glaivekiyo и Saintontas. Я не просто «выполняю проекты»; я создаю незабываемые визуальные впечатления. Будь то создание сложных композиций в After Effects или разработка кинематографичных вступлений, моя цель остается неизменной: создавать опыт, который не просто смотрят, а по-настоящему чувствуют.",
    'about.skill_1_title': "Моушн-дизайн",
    'about.skill_1_desc': "Развивающаяся дисциплина, которую я постоянно совершенствую, уже применяемая в создании высокоуровневой графики и динамичных гайдов по персонажам, вдохновленных игровой эстетикой.",
    'about.skill_2_title': "Видеомонтаж",
    'about.skill_2_desc': "Способен воплотить любое видение в жизнь, превращая идеи в кинематографичные, захватывающие видео с сильным визуальным повествованием.",
    'about.skill_3_title': "Саунд-дизайн",
    'about.skill_3_desc': "Увлеченный звуком не меньше, чем монтажом, я улучшаю видео с помощью иммерсивного, мощного аудио, которое повышает общее качество и эмоциональность.",
    'about.skill_4_title': "Создание превью (Thumbnail Artistry)",
    'about.skill_4_desc': "Разработка превью с высокой конверсией, которые мгновенно привлекают внимание и стимулируют клики благодаря сильной композиции и визуальной ясности.",
    'about.skill_5_title': "VFX и Маскинг",
    'about.skill_5_desc': "Опыт, накопленный за годы создания AMV: мастерство ротоскопирования, маскинга и композитинга в Adobe After Effects и Premiere Pro для значительного улучшения визуальной глубины и лоска.",
    'about.skill_6_title': "Frontend Разработка",
    'about.skill_6_desc': "Создание адаптивных, визуально выверенных интерфейсов, объединяющих дизайн и функциональность, с акцентом на плавное взаимодействие и высокую производительность.",
    'about.soft_1_title': "Adobe After Effects",
    'about.soft_1_desc': "Специалист по сложному кейфреймингу, моушн-графике и высококлассному VFX.",
    'about.soft_2_title': "Adobe Premiere Pro",
    'about.soft_2_desc': "Эксперт в структурировании длинных нарративов и быстром монтаже.",
    'about.soft_3_title': "Adobe Photoshop",
    'about.soft_3_desc': "Продвинутая цифровая обработка для создания эффектных статичных ассетов и превью.",
    'about.soft_4_title': "Sony Vegas Pro",
    'about.soft_4_desc': "Базовый опыт; фундамент моей карьеры монтажера и ритмичного стиля «потока».",
    'about.edu_1_title': "Магистр наук: Информатика",
    'about.edu_1_desc': "Углубленное изучение информационных систем и алгоритмической логики. Эта академическая база позволяет мне подходить к сложным структурам проектов и управлению данными с системной, высокоуровневой перспективы.",
    'about.edu_2_title': "Бакалавр наук: Компьютерная инженерия",
    'about.edu_2_desc': "Фундаментальные инженерные принципы. Мой опыт в аппаратной архитектуре и оптимизации систем дает явное преимущество в управлении тяжелыми нагрузками рендеринга и сложными интеграциями ПО.",
    'about.edu_3_title': "Профессиональный диплом: Цифровой дизайн",
    'about.edu_3_desc': "Мультидисциплинарная программа, где я преодолел разрыв между Front-End разработкой, профессиональным видеомонтажом и визуальной ретушью. Здесь мои технические инженерные корни встретились с профессиональным творческим производством.",
    'about.lang_1': "Азербайджанский",
    'about.lang_1_level': "Родной",
    'about.lang_2': "Русский",
    'about.lang_2_level': "Двуязычный",
    'about.lang_3': "Английский",
    'about.lang_3_level': "Профессиональное владение",
    'about.lang_4': "Турецкий",
    'about.lang_4_level': "Профессиональное владение",
    'about.philosophy_log': "System.Log // Философия",
    'about.philosophy_quote': "\"Мой бэкграунд компьютерного инженера означает, что я не просто использую творческое ПО; я понимаю архитектуру, стоящую за ним. Эта техническая глубина позволяет мне оптимизировать производительность, устранять неполадки в сложных пайплайнах VFX и поддерживать пиковое визуальное качество в условиях высокого давления.\"",
    'experience.ethin_role': "Дизайнер и Редактор",
    'experience.ethin_loc': "Удаленно",
    'experience.ethin_det_1': "Создание кликабельных, высококачественных превью с использованием продвинутых техник освещения и композиции.",
    'experience.ethin_det_2': "Выступал в роли преданного творческого партнера, обеспечивая оперативную поддержку всех производственных нужд.",
    'experience.ethin_det_3': "Использовал технические навыки для управления мультидисциплинарными задачами: от композиций в Photoshop до создания видео для канала без потери качества.",
    'experience.glaivekiyo_role': "Ведущий Редактор",
    'experience.glaivekiyo_loc': "Удаленно",
    'experience.glaivekiyo_det_1': "Революционизировал визуальную идентичность канала, превратив стандартные форматы в увлекательные нарративы благодаря креативному пейсингу.",
    'experience.glaivekiyo_det_2': "Освоил «монтаж для удержания» (Retention Editing), используя ритмичную нарезку и тонкие визуальные подсказки для максимального погружения зрителя.",
    'experience.glaivekiyo_det_3': "Стандартизировал высококачественные рабочие процессы, обеспечив профессиональный визуальный уровень, который переопределил производственную ценность канала.",
    'experience.glaivekiyo_det_4': "Переопределил креативное направление, сместив стиль создания видео в сторону профессиональной, эффектной эстетики.",
    'experience.braxophone_role': "Редактор",
    'experience.braxophone_loc': "Удаленно",
    'experience.braxophone_det_1': "Выполнял высокоточный пост-продакшн, управляя детализированными циклами обратной связи, чтобы каждый кадр соответствовал элитным стандартам качества.",
    'experience.braxophone_det_2': "Освоил строгий контроль качества, предоставляя идеальные покадровые правки в течение длительных производственных циклов без ущерба для целостности проекта.",
    'experience.braxophone_det_3': "Поддерживал 100% показатель завершения проектов, демонстрируя исключительную надежность и преданность делу при соблюдении сложных и жестких сроков.",
    'experience.saintontas_role': "Моушн-дизайнер, Редактор",
    'experience.saintontas_loc': "Удаленно",
    'experience.saintontas_det_1': "Разработал уникальную A-roll графику для преобразования сложных данных в моушн-ассеты с высоким удержанием.",
    'experience.saintontas_det_2': "Спроектировал индивидуальные «Intro Edits» для гайдов по персонажам, создавая отличительные визуальные идентичности через эффектную синхронизацию.",
    'experience.saintontas_det_3': "Интегрировал продвинутые VFX и маскинг, чтобы превратить стандартные туториалы в кинематографичный опыт.",
    'experience.saintontas_det_4': "Использовал 6-летний опыт в соревновательном AMV-производстве для создания профессионального саунд-дизайна и «потока» (flow).",
    'experience.mrpokke_role': "Видеоредактор",
    'experience.mrpokke_loc': "Удаленно",
    'experience.mrpokke_det_1': "Курировал высококонверсионный видеоконтент, синтезируя сырые архивы стримов в отполированные, качественные нарративы для основного канала.",
    'experience.mrpokke_det_2': "Освоил техники удержания аудитории, выявляя и изолируя «обязательные к просмотру» моменты для стимулирования стабильного роста числа зрителей.",
    'experience.mrpokke_det_3': "Поддерживал пиковую визуальную согласованность, гарантируя, что каждое загруженное видео соответствует высоким стандартам канала по пейсингу и ясности.",
    'experience.villainarc_role': "Редактор",
    'experience.villainarc_loc': "Удаленно",
    'experience.villainarc_det_1': "Создавал эффектные, стилизованные аниме-эдиты для специализированного крипто-агентства, смешивая энергичную визуальную эстетику с корпоративным месседжем для привлечения современной цифровой аудитории.",
    'experience.villainarc_det_2': "Освоил рабочие процессы с быстрым циклом для серий видео большого объема, обеспечивая профессиональное визуальное качество при соблюдении динамичных требований криптоиндустрии.",
  },
  zh: {
    'nav.about': '关于我',
    'nav.presentation': '展示',
    'nav.experience': '经验',
    'nav.services': '服务',
    'nav.awards': '奖项',
    'nav.work': '作品',
    'nav.contact': '联系方式',
    'hero.title': '创意开发者',
    'hero.subtitle': '构建数字体验',
    'hero.cta': '查看作品',
    'hero.editor': '剪辑师',
    'hero.award_winning': '[ 屡获殊荣的视频剪辑师和动态设计师 ]',
    'hero.sys_status': 'SYS.STATUS: 最佳',
    'hero.mem_usage': 'MEM.USAGE: 42.8%',
    'hero.db_conn': 'DB.CONN: 已建立',
    'hero.target': 'TARGET: 已识别',
    'hero.mode': 'MODE: 创意',
    'hero.vfx': 'VFX_PIPELINE: 活跃',
    'hero.featured': '精选档案',
    'hero.scroll': '滚动',
    'about.title': '关于我',
    'about.bio': '个人简介',
    'about.skills': '技能',
    'about.software': '软件工具',
    'about.education': '教育背景',
    'about.languages': '语言',
    'about.philosophy': '理念',
    'about.frontend': '前端开发',
    'about.video': '视频剪辑',
    'about.sound': '音效设计',
    'about.motion': '动态设计',
    'presentation.title': '展示',
    'presentation.subtitle': '作品集展示',
    'presentation.status': '状态:',
    'presentation.online': '在线',
    'presentation.data_stream': '数据流_活跃',
    'presentation.encryption': '加密: 无',
    'presentation.open_external': '外部打开',
    'experience.title': '经验',
    'experience.personal_log': '个人数据日志',
    'experience.log_1': '> 过去6年里，我一直在精进剪辑艺术。我在竞争激烈的AMV领域的背景教会了我完美卡点的重要性，而与顶级创作者的合作教会了我如何吸引观众。',
    'experience.log_2': '> 我不仅仅是把片段拼凑在一起，我是在构建一种体验。凭借6年的经验，我已经从赢得动漫剪辑比赛转变为为Braxaphone和Saintontas等创作者提供高水平的视频解决方案。',
    'experience.log_3': '> 目前，我正在弥合传统剪辑和动态设计之间的差距，确保您的项目不仅被观看，而且被感受到。',
    'experience.end_log': '[ 日志结束 ]',
    'services.title': '服务',
    'services.system_data': '系统数据',
    'services.analyzing': '> 分析战斗数据...',
    'services.encrypted': '[ 已加密 ]',
    'services.error': '错误_404',
    'services.warning': '[ 警告：数据损坏 ]',
    'services.scroll': '滚动以解密',
    'services.assets': '资产 &\n数据',
    'services.equipment_log': '装备日志',
    'services.gear': '装备',
    'services.desc_1': '> 使用我的自定义After Effects预设和SFX提升您的动态设计！',
    'services.desc_2': '> 实现那种高能量、屡获殊荣的外观的所有秘密。您将找到我在为顶级创作者进行日常工作流程中使用的精确动画曲线、过渡效果和声音设计要素。',
    'services.item_1_title': '50+ 标志性After Effects预设。',
    'services.item_1_desc': '适用于AE的拖放式运动曲线、故障贴图和震动。',
    'services.item_2_title': '精英“音速冲击”SFX库。',
    'services.item_2_desc': '用于有力的过渡和触觉剪辑的基本声音设计。',
    'services.item_3_title': '专业级流动过渡。',
    'services.item_3_desc': '适用于Premiere Pro和After Effects的无缝、带运动模糊的过渡。',
    'services.details': '[ 详情 ]',
    'services.acquire': '[ 获取 ]',
    'awards.title': '奖项',
    'awards.achievement_loaded': '成就数据库已加载',
    'awards.record': '记录',
    'awards.best_editing': '最佳剪辑',
    'awards.judges_choice': '评委选择奖',
    'awards.1st_place': '第一名',
    'awards.most_impactful': '最具影响力',
    'awards.1st_place_exclusive': '第一名 (独家)',
    'awards.1st_place_open': '第一名 (公开)',
    'work.title': '作品',
    'work.system_data': '[ 系统数据 // 工作日志 ] • ',
    'work.category_amvs': 'AMV / 剪辑',
    'work.category_creators': '内容创作者',
    'work.category_thumbnails': '缩略图',
    'contact.title': '联系方式',
    'contact.data_link': '数据链接',
    'contact.establish_connection': '建立连接',
    'contact.identifier': '标识符',
    'contact.name_placeholder': '[ 姓名 ]',
    'contact.comm_channel': '通信频道',
    'contact.email_placeholder': '[ 电子邮件 ]',
    'contact.payload': '有效载荷',
    'contact.message_placeholder': '[ 输入消息数据 ]',
    'contact.transmitting': '[ 正在传输数据... ]',
    'contact.transmit': '[ 传输 ]',
    'contact.data_received': '数据已接收',
    'contact.comm_established': '通信链接已建立。',
    'contact.awaiting': '等待进一步指示。',
    'contact.network_nodes': '网络节点',
    'contact.discord': 'DISCORD',
    'contact.copied': '用户名复制成功',
    'contact.youtube': 'YOUTUBE',
    'contact.twitter': 'X / TWITTER',
    'contact.secret_title': '发现秘密数据',
    'contact.secret_desc': '感谢您访问我的网站！我为这个设计倾注了心血。继续创作，保持出色。',
    'contact.close': '[ 关闭 ]',
    'about.bio_p1': "我的职业生涯并非始于视频剪辑师。我的道路始于计算机工程和编程，并获得了BSU的信息学硕士学位。虽然我重视编码背后的逻辑，但它从未与我完全产生共鸣。始终不变的是我对剪辑的热爱。",
    'about.bio_p2': "最初作为一种避风港，将动漫片段剪辑成音乐来表达我的情感，后来转变为一个竞争激烈的领域。在过去的6年里，我发展了一段以技术准确性和创造性影响力为特征的职业生涯，将我教育的工程精度与AMV冠军的纯粹热情结合起来。",
    'about.bio_p3': "我的工作深深植根于对数字艺术的热情，从赢得多个剪辑锦标赛到与Braxaphone、Glaivekiyo和Saintontas等顶级内容创作者合作。我不仅仅是“完成项目”；我创造令人难忘的视觉体验。无论我是构建复杂的After Effects合成，还是设计叙事驱动的电影开场，我的目标始终如一：创造不仅被观看，而且被真正感受到的体验。",
    'about.skill_1_title': "动态设计",
    'about.skill_1_desc': "一门我不断完善的不断发展的学科，已经应用于创建受游戏美学启发的高级图形和动态角色指南。",
    'about.skill_2_title': "视频剪辑",
    'about.skill_2_desc': "能够将任何愿景变为现实，将想法转化为具有强大视觉讲故事能力的电影般引人入胜的视频。",
    'about.skill_3_title': "声音设计",
    'about.skill_3_desc': "对声音和剪辑一样充满热情，我用身临其境、高影响力的音频增强视频，提升整体质量和情感。",
    'about.skill_4_title': "缩略图艺术",
    'about.skill_4_desc': "设计高转化率的缩略图，通过强大的构图和视觉清晰度瞬间吸引注意力并推动点击。",
    'about.skill_5_title': "视觉特效与遮罩",
    'about.skill_5_desc': "通过多年的AMV经验建立，掌握使用Adobe After Effects和Adobe Premiere Pro进行转描、遮罩和合成，以显着增强视觉深度和光泽。",
    'about.skill_6_title': "前端开发",
    'about.skill_6_desc': "构建响应迅速、视觉精致的界面，融合设计和功能，专注于流畅的交互和性能驱动的体验。",
    'about.soft_1_title': "Adobe After Effects",
    'about.soft_1_desc': "复杂关键帧、动态图形和高端视觉特效专家。",
    'about.soft_2_title': "Adobe Premiere Pro",
    'about.soft_2_desc': "长篇叙事结构和快速周转剪辑专家。",
    'about.soft_3_title': "Adobe Photoshop",
    'about.soft_3_desc': "用于高影响力静态资产和缩略图的高级数字操作。",
    'about.soft_4_title': "Sony Vegas Pro",
    'about.soft_4_desc': "传统专业知识；我剪辑生涯和节奏“流”风格的基础。",
    'about.edu_1_title': "理学硕士：信息学",
    'about.edu_1_desc': "高级专注于信息系统和算法逻辑。这一学术基础使我能够以系统、高层次的视角处理复杂的项目结构和数据管理。",
    'about.edu_2_title': "理学学士：计算机工程",
    'about.edu_2_desc': "基础工程原理。我在硬件架构和系统优化方面的背景在管理繁重的渲染工作负载和复杂的软件集成方面提供了明显的优势。",
    'about.edu_3_title': "专业文凭：数字设计",
    'about.edu_3_desc': "一个多学科项目，我弥合了前端开发、专业视频剪辑和视觉修饰之间的差距。这是我的技术工程根源与专业创意制作相遇的地方。",
    'about.lang_1': "阿塞拜疆语",
    'about.lang_1_level': "母语",
    'about.lang_2': "俄语",
    'about.lang_2_level': "双语",
    'about.lang_3': "英语",
    'about.lang_3_level': "专业工作熟练",
    'about.lang_4': "土耳其语",
    'about.lang_4_level': "专业工作熟练",
    'about.philosophy_log': "System.Log // 哲学",
    'about.philosophy_quote': "\"我作为计算机工程师的背景意味着我不仅仅使用创意软件；我了解它背后的架构。这种技术深度使我能够优化性能，排除复杂的VFX管道故障，并在高压环境中保持峰值视觉质量。\"",
    'experience.ethin_role': "设计师和剪辑师",
    'experience.ethin_loc': "远程",
    'experience.ethin_det_1': "使用先进的照明和构图技术创建可点击、高保真艺术的高影响力缩略图。",
    'experience.ethin_det_2': "作为专门的创意合作伙伴，为所有制作需求提供快速响应支持。",
    'experience.ethin_det_3': "利用技术熟练度管理从Photoshop合成到为频道创建视频的多学科任务，而不会影响质量。",
    'experience.glaivekiyo_role': "首席剪辑师",
    'experience.glaivekiyo_loc': "远程",
    'experience.glaivekiyo_det_1': "彻底改变了频道的视觉形象，通过创造性的节奏将标准格式演变为高参与度的叙事。",
    'experience.glaivekiyo_det_2': "掌握了“保留剪辑”，利用有节奏的剪辑和微妙的动作提示来最大化观众的沉浸感。",
    'experience.glaivekiyo_det_3': "标准化高保真工作流程，提供专业级的视觉质量，重新定义了频道的制作价值。",
    'experience.glaivekiyo_det_4': "重新定义创意方向，将视频制作风格转变为优先考虑专业、高影响力的美学。",
    'experience.braxophone_role': "剪辑师",
    'experience.braxophone_loc': "远程",
    'experience.braxophone_det_1': "执行高精度后期制作，管理精细的反馈循环，以确保每一帧都符合精英级别的质量标准。",
    'experience.braxophone_det_2': "掌握严格的质量保证，在延长的制作周期内提供完美的帧修改，而不会影响项目的完整性。",
    'experience.braxophone_det_3': "保持100%的项目完成率，展示了极高的可靠性和致力于满足复杂、高压期限的奉献精神。",
    'experience.saintontas_role': "动态设计师，剪辑师",
    'experience.saintontas_loc': "远程",
    'experience.saintontas_det_1': "开发了独特的A-roll图形，将复杂的数据转化为高保留率的动态资产。",
    'experience.saintontas_det_2': "为角色指南设计了定制的“Intro Edits”，通过高影响力的同步创建了独特的视觉形象。",
    'experience.saintontas_det_3': "集成了高级视觉特效和遮罩，将标准教程提升为电影体验。",
    'experience.saintontas_det_4': "利用在竞争激烈的AMV制作中6年的专业知识，提供专业级的声音设计和“流”。",
    'experience.mrpokke_role': "视频剪辑师",
    'experience.mrpokke_loc': "远程",
    'experience.mrpokke_det_1': "策划高参与度的视频内容，将原始流媒体档案合成为主频道抛光、高质量的叙事。",
    'experience.mrpokke_det_2': "掌握受众保留技术，识别和隔离“必看”时刻，以推动一致的观众增长。",
    'experience.mrpokke_det_3': "保持峰值视觉一致性，确保每次上传都符合频道在节奏和清晰度方面的高标准。",
    'experience.villainarc_role': "剪辑师",
    'experience.villainarc_loc': "远程",
    'experience.villainarc_det_1': "为一家专门的加密机构制作了高影响力、风格化的动漫剪辑，将高能视觉美学与企业信息相结合，以吸引现代数字原生受众。",
    'experience.villainarc_det_2': "掌握了高容量视频系列的快速周转工作流程，确保了专业级的视觉质量，同时满足了加密行业快节奏的需求。",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
